### ISSUE TITLE
This was listed in the app on Chrome Web Store as 'support'

### ISSUE THREAD

**Issue by kcstarr** [shishirsharma/MyS3Browser#1]
I'm unable to find a support link for this extension. Perhaps I need to look elsewhere?

**Comment by kcstarr** [comment]
I shud hve been more diligent prior to writing my initial comment. I need an app/ext which opens larger files. Sorry to bother u. John

**Comment by shishirsharma** [comment]
Assuming that you want to download large files from s3, This extension should provided you a presigned link. You can right click on the file name and copy link. You can then use apps like "download managers" to download a large file from s3. 

Does this answers you question.?
