### ISSUE TITLE
Inability to delete empty folder. 

### ISSUE THREAD

**Issue by sanjawirch** [shishirsharma/MyS3Browser#12]
To delete an unwanted folder, apparently you're not supposed to have anything in it. 

There is nothing in the Google+Webmaster folder.
![screen shot 2018-04-12 at 10 28 01 am](https://user-images.githubusercontent.com/4224902/38683795-496f27a2-3e3c-11e8-8354-35084be1292b.png)
I still can't seem to delete it.

**Comment by shishirsharma** [comment]
There was a bug,  Which prevented from showing content to folders with spaces in the name. This fixes it. https://github.com/shishirsharma/MyS3Browser/pull/15
