### ISSUE TITLE
Uploaded files are broken

### ISSUE THREAD

**Issue by vrobik** [shishirsharma/MyS3Browser#18]
Hello,

thanks for a great extension, but i have a problem with uploaded files.

Upload works well, i see uploaded files in the list, but all are broken when i try to access it,
i test it with pdf, png, jpg, txt all seems to be broken
here is an example of uploaded file: https://cdnmib.iconpeak.com/emails/test.png
and this one is a good one: https://cdnmib.iconpeak.com/emails/logo.png

Thanks

**Comment by shishirsharma** [comment]
Thanks, Let me have a look.

**Comment by vrobik** [comment]
Thanks for quick fix

**Comment by shishirsharma** [comment]
Can you please confirm that it worked for you ?

**Comment by vrobik** [comment]
Yes, its working without problems
