### ISSUE TITLE
Delete file

### ISSUE THREAD

**Issue by chaitanyathengdi** [shishirsharma/MyS3Browser#2]
I saw a lot of your comments on this page:
https://chrome.google.com/webstore/detail/extended-s3-browser/ddmmmnnbkhpkgnkafpflhaoohifpdkmg

I have used both, and I must say, there are a lot of bugs in this than in the other extension.
Please release fixes for those bugs.

Some of the bugs I found:

- no option to delete a file.

**Comment by shishirsharma** [comment]
@chaitanyathengdi I am committed to fixing these issue. If you are interested you can help me identify these issues. I will try to split this feedback into 3 bugs and will start from there.

**Comment by shishirsharma** [comment]
I have made to new issue related to buggy UI & broken search. I will consider this feedback as request to delete file

**Comment by shishirsharma** [comment]
Fixed https://github.com/shishirsharma/MyS3Browser/commit/8ee3d1460a4e1a82fa9b036787289dc2c229e914
