### ISSUE TITLE
Content in subfolder doesn't show up

### ISSUE THREAD

**Issue by sanjawirch** [shishirsharma/MyS3Browser#5]
Some of the folders contain the files, however, other folders even though they have files in them, do not show up. 

![screen shot 2018-01-02 at 5 39 39 pm](https://user-images.githubusercontent.com/4224902/34502940-f104b128-efe3-11e7-966a-4abf73166dac.png)

On a different S3 tool.. it shows:
![screen shot 2018-01-02 at 5 40 08 pm](https://user-images.githubusercontent.com/4224902/34502948-00f37ccc-efe4-11e7-8898-fd5f2487a60e.png)

**Comment by shishirsharma** [comment]
Will it be possible for you to open inspector [ ⌥ + ⌘ + i ] and see if there are any error on console?

**Comment by shishirsharma** [comment]
I found the issue, Will fix this.

**Comment by shishirsharma** [comment]
This is fixed in 208cc39fd52da7c3fbdeb67092f73f53be8162c6
