### ISSUE TITLE
China Region don't support

### ISSUE THREAD

**Issue by lijiantang** [shishirsharma/MyS3Browser#8]
region：cn-north-1
endpoint：s3.cn-north-1.amazonaws.com.cn

**Comment by shishirsharma** [comment]
Thanks for reporting.

**Comment by shishirsharma** [comment]
@lijiantang as a stopgap while I fix this. Leave Region empty and save your credentials. Then click on bucket selector. (bucket selector will look wired and empty but once you click it should have all your buckets.)

**Comment by shishirsharma** [comment]
This should fix it. https://github.com/shishirsharma/MyS3Browser/pull/15
