### ISSUE TITLE
Inability to navigate back 

### ISSUE THREAD

**Issue by sanjawirch** [shishirsharma/MyS3Browser#9]
Once you go into a nested folder, it is not possible to navigate backwards. For example:
![screen shot 2018-02-13 at 9 36 33 am](https://user-images.githubusercontent.com/4224902/36155114-7a3d2aa0-10a1-11e8-9616-2c7e6d4444b3.png)

I can't get back to the Adding Pages folder or to the root folder support-documentation. 

I always have to restart the process again.

**Comment by shishirsharma** [comment]
@sanjawirch You can either click on breadcrumbs (Amazone S3:// support-documentaion /adding new page)

Or you can press browser's back both should work. (This is useful during multipage pagination )

Does this help's you?

**Comment by sanjawirch** [comment]
The breadcrumbs don't work. They aren't clickable links.. neither does the back button. It's greyed out.

**Comment by shishirsharma** [comment]
@sanjawirch I don't think you are using MyS3Browser. This is how it is supposed to look like. Your screenshot looks different 
![screen shot 2018-02-26 at 10 50 24 am](https://user-images.githubusercontent.com/476201/36654484-026dccea-1ae3-11e8-8c23-d25907c57b31.png)

**Comment by sanjawirch** [comment]
Yep.. you're right.. My bad. Sorry about that. I've been trying so many different ones to see which works best and must have confused that with yours. 

Is there a way to delete an unwanted folder? I don't want to have the one that says Google + Webmaster

![screen shot 2018-02-26 at 10 49 14 am](https://user-images.githubusercontent.com/4224902/36680053-bce81b12-1ae2-11e8-84b6-9fafb35e3e8d.png)

**Comment by shishirsharma** [comment]
The only way to delete a folder in AWS is to delete everything inside it. :)

**Comment by sanjawirch** [comment]
There is nothing in the Google+Webmaster folder. 
![screen shot 2018-04-12 at 10 28 01 am](https://user-images.githubusercontent.com/4224902/38683795-496f27a2-3e3c-11e8-8354-35084be1292b.png)
I still can't seem to delete it.

**Comment by shishirsharma** [comment]
Ok, I will have a look. Will you be interested in opening a new GitHub issue for delete specific problem?
